name: "re-release"

on: 
  push:
    branches:
      - master

jobs:
  re-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Delete
        uses: actions/github-script@v9.0.0
        with:
            script: |
                const { owner, repo } = context.repo
                const { data: { id } } = await github.repos.getLatestRelease({ owner, repo })
                await github.repos.deleteRelease({ owner, repo, release_id: id })

      - name: Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          name: latest
          tag_name: latest
